name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Reopen Pull Request
        uses: juliangruber/octokit-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: pulls.create
          title: Test
          head: master
          base: master
      - name: Merge Pull Request
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
